import React, { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { generateStudyPlan } from '../../lib/studyPlanService';
import { useNavigate } from 'react-router-dom';
import EmptyState from '../EmptyState/EmptyState';

export default function StudyPlan({ studyPlanData }) {
  const { currentUser } = useAuth();
  const navigate = useNavigate();
  const [activeWeek, setActiveWeek] = useState(0);
  const [isGenerating, setIsGenerating] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0);
  const [errorMsg, setErrorMsg] = useState('');

  // Fallback if no study plan exists yet
  const plan = studyPlanData?.plan_json;
  
  const handleRegenerate = async () => {
    setIsGenerating(true);
    setErrorMsg('');
    
    // Cycle loading text
    const interval = setInterval(() => {
      setLoadingStep(prev => (prev + 1) % 4);
    }, 3000);

    try {
      const res = await generateStudyPlan(currentUser.id);
      if (res.success) {
        window.location.reload(); // Reload to fetch fresh data
      } else {
        setErrorMsg(res.message);
      }
    } catch (e) {
      setErrorMsg(e.message || "Something went wrong.");
    } finally {
      clearInterval(interval);
      setIsGenerating(false);
    }
  };

  const loadingMessages = [
    "Analysing your last 10 sessions...",
    "Identifying your weak areas...",
    "Building your personalised schedule...",
    "Almost ready..."
  ];

  if (isGenerating) {
    return (
      <div style={{ background: '#111', padding: '3rem', borderRadius: '12px', textAlign: 'center', marginTop: '2rem' }}>
        <h2 style={{ color: '#fff', marginBottom: '2rem' }}>Creating your Study Plan</h2>
        <div style={{ 
          width: '60%', 
          height: '6px', 
          background: 'rgba(255,255,255,0.1)', 
          margin: '0 auto 1.5rem', 
          borderRadius: '4px',
          overflow: 'hidden',
          position: 'relative'
        }}>
          <div style={{
            position: 'absolute',
            top: 0, bottom: 0, left: 0,
            width: '50%',
            background: '#b06aff',
            animation: 'slide 1.5s infinite ease-in-out',
            borderRadius: '4px'
          }}></div>
        </div>
        <p style={{ color: '#9CA3AF', fontSize: '1.1rem', transition: 'all 0.3s ease' }}>
          {loadingMessages[loadingStep]}
        </p>
        <style>{`
          @keyframes slide {
            0% { left: -50%; }
            100% { left: 100%; }
          }
        `}</style>
      </div>
    );
  }

  // If no plan exists, show a voiced empty state to generate the first one
  if (!plan) {
    return (
      <div style={{ marginTop: '2rem' }}>
        <EmptyState
          message="No plan yet — generate one and Alex will map out exactly what to practice and when."
        />
        <div style={{ marginTop: 16, textAlign: 'center' }}>
          <button
            onClick={handleRegenerate}
            style={{
              background: 'transparent',
              color: '#fff',
              padding: '10px 24px',
              borderRadius: '8px',
              border: '1px solid #333',
              cursor: 'pointer',
              fontWeight: '600',
              fontSize: 14,
            }}
          >
            Generate my study plan
          </button>
          {errorMsg && <p style={{ color: '#ff6b6b', marginTop: '1rem' }}>{errorMsg}</p>}
        </div>
      </div>
    );
  }

  // Time calculations for regenerate button
  let canRegenerate = true;
  let hoursLeft = 0;
  if (studyPlanData?.generated_at) {
    const hoursSince = (Date.now() - new Date(studyPlanData.generated_at).getTime()) / (1000 * 60 * 60);
    if (hoursSince < 24) {
      canRegenerate = false;
      hoursLeft = Math.ceil(24 - hoursSince);
    }
  }

  const readinessColor = plan.predicted_score_at_interview >= 7.5 ? '#2dd4a0' : (plan.predicted_score_at_interview >= 6 ? '#ffcc60' : '#ff6b6b');
  const activeWeekData = plan.weeks && plan.weeks[activeWeek] ? plan.weeks[activeWeek] : null;

  return (
    <div style={{ marginTop: '3rem', color: '#fff' }}>
      
      {/* HEADER ROW */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', marginBottom: '1.5rem', gap: '1rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <h2 style={{ margin: 0, fontSize: '1.5rem' }}>Your Study Plan</h2>
          <span style={{ background: 'rgba(176, 106, 255, 0.15)', color: '#b06aff', padding: '4px 8px', borderRadius: '12px', fontSize: '0.75rem', fontWeight: 'bold', border: '1px solid rgba(176,106,255,0.3)' }}>
            <i className="fa-solid fa-robot" style={{ marginRight: '6px' }}></i>AI-generated by Claude
          </span>
        </div>
        <button 
          onClick={handleRegenerate}
          disabled={!canRegenerate}
          style={{ 
            background: canRegenerate ? 'transparent' : 'rgba(255,255,255,0.05)', 
            color: canRegenerate ? '#b06aff' : '#666', 
            border: canRegenerate ? '1px solid #b06aff' : '1px solid #333', 
            padding: '8px 16px', 
            borderRadius: '8px', 
            cursor: canRegenerate ? 'pointer' : 'not-allowed',
            fontWeight: '600'
          }}
        >
          {canRegenerate ? 'Regenerate →' : `Next regeneration in ${hoursLeft}h`}
        </button>
      </div>

      <div style={{ background: 'rgba(255,255,255,0.03)', padding: '1.5rem', borderRadius: '12px', marginBottom: '2rem', borderLeft: '4px solid #b06aff' }}>
        <p style={{ margin: 0, color: '#e8e8e8', lineHeight: '1.6' }}>{plan.summary}</p>
        {errorMsg && <p style={{ color: '#ff6b6b', marginTop: '1rem', marginBottom: 0 }}>{errorMsg}</p>}
      </div>

      {/* READINESS STRIP */}
      <div style={{ background: `${readinessColor}15`, border: `1px solid ${readinessColor}30`, padding: '1rem 1.5rem', borderRadius: '12px', marginBottom: '2rem', display: 'flex', alignItems: 'center', gap: '12px' }}>
        <i className="fa-solid fa-chart-line" style={{ color: readinessColor, fontSize: '1.25rem' }}></i>
        <p style={{ margin: 0, color: '#fff', fontSize: '1rem' }}>{plan.readiness_trajectory}</p>
      </div>

      {/* TOP 3 PRIORITIES */}
      <h3 style={{ fontSize: '1.25rem', marginBottom: '1rem' }}>Top 3 Priorities</h3>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '1.5rem', marginBottom: '3rem' }}>
        {plan.top_3_priorities?.map((priority, idx) => (
          <div key={idx} style={{ background: '#111', padding: '1.5rem', borderRadius: '12px', borderLeft: `4px solid ${['#ff6b6b', '#ffcc60', '#60cfff'][idx]}` }}>
            <div style={{ color: '#888', fontSize: '0.875rem', fontWeight: 'bold', marginBottom: '8px' }}>PRIORITY {idx + 1}</div>
            <p style={{ margin: 0, color: '#e8e8e8' }}>{priority}</p>
          </div>
        ))}
      </div>

      {/* WEEK VIEW */}
      {plan.weeks && plan.weeks.length > 0 && (
        <div style={{ background: '#111', borderRadius: '12px', padding: '2rem' }}>
          
          {/* Tabs */}
          <div style={{ display: 'flex', borderBottom: '1px solid #333', marginBottom: '2rem', overflowX: 'auto' }}>
            {plan.weeks.map((w, idx) => (
              <button
                key={idx}
                onClick={() => setActiveWeek(idx)}
                style={{
                  background: 'transparent',
                  border: 'none',
                  color: activeWeek === idx ? '#fff' : '#888',
                  padding: '12px 24px',
                  fontSize: '1rem',
                  fontWeight: activeWeek === idx ? 'bold' : 'normal',
                  borderBottom: activeWeek === idx ? '2px solid #b06aff' : '2px solid transparent',
                  cursor: 'pointer',
                  whiteSpace: 'nowrap'
                }}
              >
                Week {w.week_number}
              </button>
            ))}
          </div>

          {/* Active Week Content */}
          {activeWeekData && (
            <div>
              <h3 style={{ fontSize: '1.5rem', marginBottom: '1rem', color: '#fff' }}>{activeWeekData.focus}</h3>
              <div style={{ background: 'rgba(255, 204, 96, 0.1)', border: '1px solid rgba(255, 204, 96, 0.2)', padding: '1rem', borderRadius: '8px', color: '#ffcc60', marginBottom: '2rem' }}>
                <i className="fa-solid fa-bullseye" style={{ marginRight: '8px' }}></i>
                <strong>Goal this week:</strong> {activeWeekData.weekly_goal}
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', marginBottom: '2rem' }}>
                {activeWeekData.daily_sessions?.map((session, idx) => (
                  <div key={idx} style={{ background: '#1a1a2a', border: '1px solid #2a2a4a', borderRadius: '12px', padding: '1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem' }}>
                    
                    <div style={{ flex: '1 1 300px' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '12px' }}>
                        <span style={{ fontSize: '1.1rem', fontWeight: 'bold' }}>{session.day}</span>
                        <span style={{ background: 'rgba(96, 207, 255, 0.15)', color: '#60cfff', padding: '2px 8px', borderRadius: '12px', fontSize: '0.75rem', textTransform: 'uppercase' }}>
                          {session.session_type}
                        </span>
                        <span style={{ background: 'rgba(255, 255, 255, 0.1)', color: '#ccc', padding: '2px 8px', borderRadius: '12px', fontSize: '0.75rem', textTransform: 'uppercase' }}>
                          {session.difficulty}
                        </span>
                        <span style={{ color: '#888', fontSize: '0.875rem' }}><i className="fa-regular fa-clock"></i> {session.duration_minutes} min</span>
                      </div>
                      <h4 style={{ margin: '0 0 8px 0', fontSize: '1.1rem', color: '#e8e8e8' }}>{session.focus_area}</h4>
                      <p style={{ margin: 0, color: '#9CA3AF', fontSize: '0.9rem' }}>{session.why}</p>
                    </div>

                    <button 
                      onClick={() => {
                        window.location.href = `/?autoStart=true&type=${session.session_type}&difficulty=${session.difficulty}`;
                      }}
                      style={{ background: '#fff', color: '#000', border: 'none', padding: '10px 20px', borderRadius: '8px', fontWeight: '600', cursor: 'pointer', whiteSpace: 'nowrap' }}
                    >
                      Practice this →
                    </button>
                    
                  </div>
                ))}
              </div>

              {/* Resources */}
              {activeWeekData.resources && activeWeekData.resources.length > 0 && (
                <div>
                  <h4 style={{ fontSize: '1rem', color: '#888', marginBottom: '1rem' }}>Recommended Resources</h4>
                  <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
                    {activeWeekData.resources.map((res, idx) => (
                      <span key={idx} style={{ background: 'rgba(255,255,255,0.05)', color: '#ccc', padding: '6px 12px', borderRadius: '16px', fontSize: '0.875rem', border: '1px solid rgba(255,255,255,0.1)' }}>
                        <i className="fa-solid fa-link" style={{ marginRight: '6px' }}></i> {res}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {/* PREDICTED SCORE CALLOUT */}
      <div style={{ marginTop: '2rem', background: '#111', padding: '2rem', borderRadius: '12px', display: 'flex', alignItems: 'center', gap: '2rem', borderTop: `4px solid ${readinessColor}` }}>
        <div style={{ fontSize: '3.5rem', fontWeight: 'bold', color: readinessColor }}>
          {plan.predicted_score_at_interview}
        </div>
        <div>
          <h3 style={{ margin: '0 0 8px 0', fontSize: '1.25rem' }}>Predicted score at your interview</h3>
          <p style={{ margin: 0, color: '#9CA3AF' }}>Based on your current improvement rate</p>
        </div>
      </div>
      
    </div>
  );
}
