CREATE TABLE IF NOT EXISTS company_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_name text NOT NULL,
  interview_style text NOT NULL,
  key_values text[],
  common_question_themes text[],
  red_flags text[],
  tip_for_candidate text
);

TRUNCATE TABLE company_profiles;

INSERT INTO company_profiles (company_name, interview_style, key_values, common_question_themes, red_flags, tip_for_candidate) VALUES
('Google', 'Heavy on algorithmic thinking and system design. Interviewers probe deeply — one good answer leads to three harder follow-ups. Leadership principles rarely asked. Culture fit is assessed through intellectual curiosity and structured reasoning.', ARRAY['analytical thinking', 'scalability', 'clarity of thought', 'first principles'], ARRAY['system design at scale', 'graph and tree algorithms', 'ambiguous problem solving', 'why Google'], ARRAY['vague answers without structure', 'not thinking aloud', 'skipping complexity analysis'], 'Think out loud always. Google values how you think more than whether you get the right answer.'),
('Amazon', 'Deeply behavioral, driven by 16 Leadership Principles. Every question maps to an LP. Candidates are expected to give STAR-structured answers with specific data and measurable results. System design is also common for senior roles.', ARRAY['customer obsession', 'ownership', 'bias for action', 'frugality', 'deliver results'], ARRAY['tell me about a time you failed', 'ownership of a hard project', 'disagreed with your manager', 'built something from scratch'], ARRAY['generic answers without specific data', 'team credit without personal ownership', 'no measurable outcome in STAR'], 'Prepare 6-8 strong STAR stories. Every story should map to at least 3 different Leadership Principles.'),
('Flipkart', 'Mix of product sense, system design, and behavioral. Heavy on e-commerce domain knowledge. Values execution speed and scrappiness over perfection. Culture fit around working in ambiguity is key.', ARRAY['customer focus', 'execution speed', 'data-driven decisions', 'ownership'], ARRAY['design an e-commerce feature', 'scaling during sale events', 'trade-off between speed and quality', 'metrics for a feature launch'], ARRAY['over-engineering simple solutions', 'no awareness of Indian market context', 'no mention of data or metrics'], 'Show you understand India-scale problems — intermittent connectivity, price-sensitive users, logistics complexity.'),
('Startup', 'Fast-paced, informal, and broad. Interviewers look for generalists who can wear multiple hats. Culture fit and energy matter as much as technical skill. Expect practical take-home problems more than LeetCode.', ARRAY['adaptability', 'initiative', 'learning speed', 'impact over process'], ARRAY['what would you do in your first 30 days', 'tell me about something you built from scratch', 'how do you handle wearing many hats'], ARRAY['rigid thinking', 'needs heavy process to function', 'focused only on one specialization'], 'Show initiative. Talk about things you built, shipped, or fixed without being asked.'),
('Microsoft', 'Balanced between technical depth and growth mindset. Coding rounds use LeetCode-medium problems. Behavioral rounds focus heavily on collaboration and learning from failure. System design expected for senior roles.', ARRAY['growth mindset', 'collaboration', 'inclusion', 'customer empathy'], ARRAY['design a feature in a Microsoft product', 'conflict resolution in a team', 'most technically challenging project', 'why Microsoft'], ARRAY['fixed mindset answers', 'solo hero stories with no team mention', 'no curiosity about the product'], 'Use phrases that signal learning: "What I took away from that", "How I would approach it differently". Microsoft loves self-aware candidates.');
